name = "post"

compatibility_flags = [ "formdata_parser_supports_files" ]

kv_namespaces = [
  { binding = "FILES", id = "<ignored>", preview_id = "<ignored>" }
]

[miniflare]
routes = ["*/upload"]
kv_persist = "../data/"

[build.upload]
format = "modules"