name = "post"

compatibility_date = "2023-03-19"

kv_namespaces = [
  { binding = "Blob", id = "<ignored>", preview_id = "<ignored>" }
]

[miniflare]
routes = ["*/upload"]
kv_persist = "../data/"

[build.upload]
format = "modules"